// Generates boss-art.js from the procedural figures in tools/boss-art/.
const fs = require('fs');
const path = require('path');
const { INK, Canvas, toRuns, validate } = require('./pixlib');
const { BUILDERS } = require('./figures');

const GW = 78, GH = 44;

let out = '';
let totalRuns = 0;
const views = {};

for (const [name, build] of Object.entries(BUILDERS)) {
  const fig = build();
  const c = new Canvas(GW, GH);
  c.blit(fig, Math.round((GW - fig.w) / 2), Math.round((GH - fig.h) / 2));
  const v = validate(c, name);
  if (v.problems.length) {
    console.error('PROBLEM in ' + name + ': ' + v.problems.slice(0, 5).join('; '));
    process.exit(1);
  }
  const b = c.bounds();
  views[name] = [b.x0, b.y0, b.x1 - b.x0 + 1, b.y1 - b.y0 + 1];

  const runs = toRuns(c);
  totalRuns += runs.length;

  const parts = runs.map(r => `[${r[0]},${r[1]},${r[2]},${r[3]},'${r[4]}']`);
  let line = '';
  const lines = [];
  for (const p of parts) {
    if (line && line.length + p.length + 2 > 104) { lines.push(line + ','); line = ''; }
    line += (line ? ',' : '') + p;
  }
  lines.push(line);

  out += `  ${JSON.stringify(name)}: [\n${lines.map(l => '    ' + l).join('\n')}\n  ],\n`;
  console.error(`  ${name.padEnd(14)} view ${b.x1 - b.x0 + 1}x${b.y1 - b.y0 + 1}  ${runs.length} runs`);
}

const body =
`// =============================================================================
//  BOSS ART -- pure data. Edit this file to redesign the boss portraits.
//  game.js renders whatever is here; it contains no art of its own.
//
//  THE CONTRACT
//  ------------
//  1. Every key in \`portraits\` must match a boss name in game.js's BOSSES array,
//     exactly. It is looked up by NAME, so reordering BOSSES cannot mismatch art to
//     the wrong fight. A boss with no entry simply renders no portrait.
//
//  2. \`portraits[name]\` is a flat array of pixel runs, each one of which is
//         [column, row, width, height, inkLetter]
//     All coordinates are integers on a shared ${GW}x${GH} grid. Runs must not overlap
//     -- paint order is meaningless, later runs would just cover earlier ones.
//     A boss does NOT need to fill the grid; \`views\` below crops the camera to it.
//
//  3. \`views[name]\` is [x, y, width, height] -- a rectangle cropped tight to that
//     boss's art. This is what makes each portrait fill its frame instead of floating
//     in a big empty box, so it matters more than anything else here. Recompute it
//     with tools/boss-art/check.js after editing, or just eyeball it: it should hug
//     the outermost lit pixel on all four sides.
//
//  4. \`ink\` maps the letters used in the runs to CSS colours. Anything not in this
//     table renders as the fallback grey.
//
//  5. Do not add a <script> tag, a module wrapper, or any code. This file only
//     assigns one global. Keep it loadable as a plain classic script.
//
//  REDESIGNING?  Two routes:
//   - PROCEDURAL (recommended): the figures are generated by tools/boss-art/, where
//     each boss is a short function built from ellipses, polys, tapered limbs and
//     outlines. Adjust coordinates there and run \`node tools/boss-art/build.js\` to
//     regenerate this file. Far easier than placing 2,700 runs by hand.
//   - BY HAND: fine for a single boss, unpleasant for a full set. run
//     \`node tools/boss-art/check.js\` afterwards to catch mistakes.
//
//  CHECK YOUR WORK:  node tools/boss-art/check.js     (overlaps, out-of-bounds,
//  unknown inks, stale names, empty bosses)
//  PREVIEW:          open boss_sheet.html            (all ten, at in-game size)
// =============================================================================

window.BOSS_ART = {
  // Letter -> CSS colour. One shared palette for every boss, which is what keeps the
  // set looking like a set. Add letters freely; nothing else needs updating.
  ink: ${JSON.stringify(INK, null, 4).replace(/\n/g, '\n  ')},

  // [x, y, width, height] -- the camera rectangle, cropped tight to each boss.
  views: ${JSON.stringify(views, null, 4).replace(/\n/g, '\n  ')},

  // The art itself. ${totalRuns} runs across 10 bosses.
  portraits: {
${out}  },
};
`;

const dest = path.join(__dirname, '..', '..', 'boss-art.js');
fs.writeFileSync(dest, body);
console.error(`\nwrote boss-art.js — ${totalRuns} runs, ${(body.length / 1024).toFixed(1)} KB`);
